Repository wasabee-project/Wasabee-IITC, pull requests merged in 2022-01, with the labels that each got.

#321 Allow duplicate marker type on a portal
  src/code/dialogs/markerAddDialog.js
  src/code/dialogs/markerChangeDialog.js
  src/code/model/operation.ts
Labels: enhancement

#325 Missing translatable strings
  .eslintrc.json
  eslint-local-rules.js
  package.json
  src/code/buttons/uploadButton.js
  src/code/buttons/wasabeeButton.js
  src/code/dialogs/authDialog.js
  src/code/dialogs/autodraws/fanfield.js
  src/code/dialogs/autodraws/homogeneous.js
  src/code/dialogs/autodraws/madrid.js
  src/code/dialogs/autodraws/multimaxDialog.js
  src/code/dialogs/autodraws/onionfield.js
  src/code/dialogs/blockersList.js
  src/code/dialogs/checklist.js
  src/code/dialogs/importDialog.js
  src/code/dialogs/linkListDialog.js
  src/code/dialogs/manageTeamDialog.js
  src/code/dialogs/markerAddDialog.js
  src/code/dialogs/onlineAgentList.js
  src/code/dialogs/opPerms.js
  src/code/dialogs/opSettings.js
  src/code/dialogs/opsDialog.js
  src/code/dialogs/teamListDialog.js
  src/code/dialogs/teamMembershipList.js
  src/code/dialogs/trawl.js
  src/code/dialogs/zoneDialog.js
  src/code/dialogs/zoneSetColor.js
  src/code/firebaseSupport.ts
  src/code/model/operation.ts
  src/code/toolbox.ts
  src/code/translations/English.json
  src/code/ui/anchor.js
  src/code/ui/marker.js
  src/code/uiCommands.ts
Labels: In Testing

#324 Bulk marker add
  src/code/css/wasabee.css
  src/code/dialogs/markerAddDialog.js
  src/code/translations/Danish.json
  src/code/translations/English.json
  src/code/translations/Filipino.json
  src/code/translations/French.json
  src/code/translations/German.json
  src/code/translations/Italian.json
  src/code/translations/Portuguese.json
  src/code/translations/Russian.json
  src/code/translations/Spanish.json
Labels: enhancement, In Testing
